# Generated by Django 5.1.1 on 2024-10-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان ایده نوآورانه')),
                ('goal', models.CharField(max_length=255, verbose_name='هدف ایده')),
                ('importance', models.TextField(verbose_name='ضرورت و اهمیت ایده')),
                ('details', models.TextField(verbose_name='توضیحات تکمیلی')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('work_place', models.CharField(max_length=100, verbose_name='محل اشتغال')),
                ('major', models.CharField(max_length=100, verbose_name='رشته تحصیلی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('identifier', models.PositiveIntegerField(verbose_name='شماره')),
            ],
        ),
    ]
