# Generated by Django 5.1.1 on 2025-01-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_idea_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleFa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('titleEn', models.CharField(max_length=255, verbose_name='عنوان انگلیسی')),
                ('keyWords', models.TextField(verbose_name='کلمات کلیدی')),
                ('projectType', models.CharField(choices=[('research', 'پروژه پژوهشی'), ('phd', 'پایان نامه دکتری'), ('master', 'پایان نامه کارشناسی ارشد')], max_length=100, verbose_name='نوع پروژه')),
                ('research_pole', models.CharField(max_length=255, verbose_name='قطب پژوهشی')),
                ('research_pole_username', models.CharField(max_length=255, verbose_name='نام موسسه')),
                ('developer', models.CharField(max_length=255, verbose_name='توسعه دهنده')),
                ('costumer', models.CharField(max_length=255, verbose_name='متقاضی')),
                ('nameAndNumberofPlan', models.CharField(max_length=255, verbose_name='نام و شماره طرح')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('work_place', models.CharField(max_length=100, verbose_name='محل اشتغال')),
                ('major', models.CharField(max_length=100, verbose_name='رشته تحصیلی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
            ],
        ),
        migrations.RemoveField(
            model_name='idea',
            name='email',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='major',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='work_place',
        ),
        migrations.AddField(
            model_name='idea',
            name='final_average',
            field=models.FloatField(blank=True, null=True, verbose_name='میانگین نهایی'),
        ),
        migrations.AddField(
            model_name='idea',
            name='is_finally_approved',
            field=models.BooleanField(default=False, verbose_name='تایید نهایی'),
        ),
        migrations.AddField(
            model_name='idea',
            name='is_in_meeting',
            field=models.BooleanField(default=False, verbose_name='در حال ارزیابی'),
        ),
        migrations.AddField(
            model_name='idea',
            name='judge1_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='امتیاز داور اول'),
        ),
        migrations.AddField(
            model_name='idea',
            name='judge2_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='امتیاز داور دوم'),
        ),
        migrations.AddField(
            model_name='idea',
            name='judge3_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='امتیاز داور سوم'),
        ),
        migrations.AddField(
            model_name='idea',
            name='judge4_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='امتیاز داور چهارم'),
        ),
    ]
