# Generated by Django 5.1.1 on 2025-01-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_proposal_user_remove_idea_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nationalID',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
    ]
