# Generated by Django 5.1.1 on 2025-02-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_user_nationalid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='idea',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
    ]
