# Generated by Django 5.1.1 on 2025-03-03 09:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_delete_user_alter_idea_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='final_average',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='is_in_meeting',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='verification',
        ),
        migrations.AddField(
            model_name='idea',
            name='first_confirmation',
            field=models.BooleanField(default=False, verbose_name='تایید اولیه'),
        ),
        migrations.AddField(
            model_name='idea',
            name='judge1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=' داور اول'),
        ),
        migrations.AddField(
            model_name='idea',
            name='judge2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=' داور دوم'),
        ),
        migrations.AddField(
            model_name='idea',
            name='judge3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=' داور سوم'),
        ),
        migrations.AddField(
            model_name='idea',
            name='judge4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=' داور چهارم'),
        ),
        migrations.AddField(
            model_name='idea',
            name='keywords',
            field=models.CharField(default='کلید', max_length=255, verbose_name='کلمات کلیدی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='proposal',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.proposal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='proposal_confirmation',
            field=models.BooleanField(default=False, verbose_name='تایید پروپوزال'),
        ),
        migrations.AddField(
            model_name='idea',
            name='proposal_modifacation',
            field=models.BooleanField(default=False, verbose_name='اصلاح پروپوزال'),
        ),
        migrations.AddField(
            model_name='idea',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contribution_percent_idea', models.PositiveIntegerField(help_text='Percentage of contribution', validators=[django.core.validators.MaxValueValidator(100)])),
                ('contribution_percent_project', models.PositiveIntegerField(help_text='Percentage of contribution', validators=[django.core.validators.MaxValueValidator(100)])),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='dashboard.idea')),
            ],
        ),
    ]
