# Generated by Django 5.1.1 on 2025-03-05 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_idea_final_average_remove_idea_is_in_meeting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='identifier',
            field=models.CharField(max_length=20, verbose_name='شماره'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.proposal'),
        ),
    ]
