# Generated by Django 5.1.1 on 2025-03-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_idea_identifier_alter_idea_proposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='first_confirmation',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='is_finally_approved',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='proposal_confirmation',
        ),
        migrations.AddField(
            model_name='idea',
            name='status',
            field=models.CharField(default=1, max_length=20, verbose_name='وضعیت'),
            preserve_default=False,
        ),
    ]
