# Generated by Django 5.1.1 on 2025-03-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_idea_first_confirmation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='keyWords',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='titleEn',
            new_name='projectTitleEn',
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='titleFa',
            new_name='projectTitleFa',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='projectType',
            field=models.CharField(choices=[('research', 'پروژه پژوهشی'), ('phd', 'پایان نامه دکتری'), ('masters', 'پایان نامه کارشناسی ارشد')], max_length=100, verbose_name='نوع پروژه'),
        ),
    ]
