# Generated by Django 5.1.1 on 2025-03-16 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_keywords_proposal_keywords_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='judge1',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='judge1_score',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='judge2',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='judge2_score',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='judge3',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='judge3_score',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='judge4',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='judge4_score',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='proposal_modifacation',
        ),
        migrations.CreateModel(
            name='JudgeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_judges', to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='dashboard.idea')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('idea', 'judge')},
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_time', models.DateTimeField(null=True)),
                ('presentation_file', models.FileField(null=True, upload_to='presentations/')),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presentation', to='dashboard.idea')),
            ],
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
    ]
