# Generated by Django 5.1.1 on 2025-03-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_idea_judge1_remove_idea_judge1_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presentation',
            name='average_grade',
            field=models.FloatField(null=True),
        ),
    ]
