# Generated by Django 5.1.1 on 2025-03-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_presentation_approved_presentation_average_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='research_pole_username',
            new_name='researchPoleUsername',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='costumer',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='research_pole',
        ),
        migrations.AddField(
            model_name='proposal',
            name='achievement',
            field=models.TextField(default=1, verbose_name='دستاورد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='application',
            field=models.TextField(default=1, verbose_name='کاربرد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='chiefName',
            field=models.CharField(default=1, max_length=255, verbose_name='نام رئیس گروه پژوهشی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='economicBenefits',
            field=models.TextField(default=1, verbose_name='صرفه اقتصادی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='finalCustomer',
            field=models.CharField(default=1, max_length=255, verbose_name='متقاضی/مشتری نهایی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='goal',
            field=models.TextField(default=1, verbose_name='هدف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='projectImportance',
            field=models.CharField(choices=[('fundamental', 'بنیادی'), ('applied', 'کاربردی'), ('developmental', 'توسعه ای'), ('studies', 'مطالعاتی')], default=1, max_length=100, verbose_name='اهمیت پروژه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='projectScale',
            field=models.CharField(choices=[('feasibility', 'امکان سنجی'), ('lab', 'آزمایشگاهی'), ('small', 'پیشتاز کوچک'), ('large', 'پیشتاز بزرگ'), ('industrial', 'صنعتی')], default=1, max_length=100, verbose_name='مقیاس پروژه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='relatedReaserch',
            field=models.TextField(default=1, verbose_name='پژوهش مرتبط'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='researchGroup',
            field=models.CharField(choices=[('research', 'پروژه پژوهشی'), ('phd', 'پایان نامه دکتری'), ('masters', 'پایان نامه کارشناسی ارشد')], default=1, max_length=100, verbose_name='گروه پژوهشی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='researchMethod',
            field=models.TextField(default=1, verbose_name='روش تحقیق'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='researchPole',
            field=models.CharField(choices=[('research', 'پروژه پژوهشی'), ('phd', 'پایان نامه دکتری'), ('masters', 'پایان نامه کارشناسی ارشد')], default=1, max_length=100, verbose_name='قطب پژوهشی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='secretaryName',
            field=models.CharField(default=1, max_length=255, verbose_name='نام دبیر تیم پژوهشی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='service',
            field=models.TextField(default=1, verbose_name='خدمات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='teamName',
            field=models.CharField(default=1, max_length=255, verbose_name='نام تیم پژوهشی'),
            preserve_default=False,
        ),
    ]
