# Generated by Django 5.1.1 on 2025-03-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personnel_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
