# Generated by Django 5.1.1 on 2025-03-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_personnel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='job',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
