# Generated by Django 5.1.1 on 2025-03-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customuser_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='personnel_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
